language: java
jdk:
  - oraclejdk7
notifications:
  email: false
install:
  - sudo mkdir lib && sudo wget http://www.spigotmc.org/resources/bungee-admin-tools.444/download?version=9384 -O lib/BAT.jar
  - mvn clean package
deploy:
    provider: releases
    api-key: "$GITHUB_OATH_TOKEN"
    file:
        - "target/UntamedChat.jar"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true